FROM golang:1.12.1 as builder
ARG LD_FLAGS

COPY ./ /go/src/{{  .ModuleName  }}/
WORKDIR /go/src/{{  .ModuleName  }}/

RUN apt-get update && apt-get install unzip
RUN make install-deptools clean build

FROM alpine:3.9
RUN apk --no-cache add ca-certificates
COPY --from=builder /go/src/{{  .ModuleName  }}/bin/{{ .Name  }} /usr/bin
ENTRYPOINT ["/usr/bin/{{ .Name  }}"]
CMD ["-h"]
