before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
archives:
  -
    id: servicebuilder
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip

brews:
  -
    name: servicebuilder
    ids:
    - servicebuilder
    tap:
      owner: cnative
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
    folder: Formula
    homepage:  https://cnative.dev
    description: A gRPC based Micro Service scaffolding in GoLang with HTTP/JSON gRPC gateway
    test: |
      system "#{bin}/servicebuilder version"
    install: |
      bin.install "servicebuilder"