env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
archive:
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
brew:
  github:
    owner: cnative
    name: homebrew-tap
  folder: Formula
  homepage:  https://cnative.dev
  description: A gRPC based Micro Service scaffolding in GoLang with HTTP/JSON gRPC gateway
  test: |
    system "#{bin}/servicebuilder version"