package iwrap

// TracingTmplt used to wrap an interface with opencensus tracing
const TracingTmplt = `
// Code generated by servicebuilder iwrap. DO NOT EDIT.

{{ .ServiceBuilderVersion }}

{{$target := .InterfaceName}}
{{$recv :=  .ReceiverSub  }}

package {{ .PackageName }}

import (
	"fmt"
	"strings"
	"context"

	"go.opencensus.io/trace"

	{{range .CustomImports}}
	"{{.}}"
	{{end}}
)

// {{ lowerCamelCase $target}}WithTrace wraps {{$target}} and records trace information
type {{ lowerCamelCase $target}}WithTrace struct {
	wrapped{{$target}}     {{$target}}
	component string
}

// {{$target}}WithTrace creates a new {{$target}} with trace
func {{$target}}WithTrace(toWrap  {{$target}}, logger *log.Logger) {{$target}} {
	component := strings.TrimPrefix(fmt.Sprintf("%T", toWrap), "*")
	logger.Debugf("{{ $target }} tracing enabled for %v", component)
	
	return &{{ lowerCamelCase $target}}WithTrace{
		wrapped{{$target}} :  toWrap,
		component: component,
	}
}

var _ {{$target}} = (*{{ lowerCamelCase $target}}WithTrace)(nil)

{{range .Methods}}
{{template "doc" . -}}
func ({{$recv}} *{{ lowerCamelCase $target}}WithTrace) {{.Name}}({{template "list" .Params}}) ({{template "list" .Returns}}) {
	ctx, span := trace.StartSpan(ctx, "{{.Name}}")
	defer span.End()

	{{template "returns" .Returns}} = {{$recv}}.wrapped{{$target}}.{{.Name}}({{template "params" .Params}}){{if isLastReturnError .Returns }}
		if {{ lastReturnName .Returns }} != nil {
			span.Annotate([]trace.Attribute{trace.StringAttribute("error", {{ lastReturnName .Returns }}.Error())}, "{{.Name}}")
		}
	{{end}}

	return {{template "returns" .Returns}}
}
{{end}}


// Healthy calls Healthy on the wrapped {{$target}}.
func ({{$recv}} *{{ lowerCamelCase $target}}WithTrace) Healthy() error {
	return {{$recv}}.wrapped{{$target}}.Healthy()
}

// Ready calls Ready on the wrapped {{$target}}.
func ({{$recv}} *{{ lowerCamelCase $target}}WithTrace) Ready() (bool, error) {
	return {{$recv}}.wrapped{{$target}}.Ready()
}

// Close calls Close on the wrapped {{$target}}.
func ({{$recv}} *{{ lowerCamelCase $target}}WithTrace) Close() error {
	return {{$recv}}.wrapped{{$target}}.Close()
}

{{define "list"}}{{range $index, $element := .}}{{if $index}}, {{end}}{{if $element.Name}}{{$element.Name}}{{end}} {{$element.Type}}{{end}}{{end}}
{{define "params"}}{{range $index, $element := .}}{{if $index}}, {{end}}{{if $element.Name}}{{$element.Name}}{{$element.Suffix}}{{end}}{{end}}{{end}}
{{define "returns"}}{{range $index, $element := .}}{{if $index}}, {{end}}{{if $element.Name}}{{$element.Name}}{{end}}{{end}}{{end}}

{{define "error"}}{{end}}

{{define "doc"}}
{{range .Doc}}
{{.}}
{{- else}}
// {{.Name}} .
{{- end}}
{{end}}
`
