version: 2.1

orbs:
  shellcheck: circleci/shellcheck@1.3.1

jobs:
  build-and-test:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - restore_cache:
          name: Restore GO Module Cache
          keys:
            - go-pkg-cache-{{ checksum "go.sum" }}
      - restore_cache:
          name: Restore Build Tools Cache
          keys:
            - tools-{{ checksum "./scripts/install_tools.sh" }}
      - run:
          name: Install Dependent Tools
          command: |
            make install-deptools
      - run:
          name: Build
          command: |
            VERSION=${CIRCLE_TAG:-$CIRCLE_BUILD_NUM} make clean build
      - run:
          name: Tests
          command: make test
          env:
            GO_TEST_FLAGS: -race
      - save_cache:
          name: Save GO Modules Cache
          key: go-pkg-cache-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
      - save_cache:
          name: Save Build Tools Cache
          key: tools-{{ checksum "./scripts/install_tools.sh" }}
          paths:
            - .tools
      - persist_to_workspace:
          root: .
          paths:
            - ./

  golangci-lint:
    docker:
      - image: circleci/golang:1.15
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - restore_cache:
          name: Restore GO Module Cache
          keys:
            - go-pkg-cache-{{ checksum "go.sum" }}
      - run:
          name: golangci-lint
          command: |
            make lint

  publish-cli:
    docker:
      - image: circleci/golang:1.15
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - restore_cache:
          name: Restore GO Module Cache
          keys:
            - go-pkg-cache-{{ checksum "go.sum" }}
      - run:
          name: Publish CLI using goreleaser
          command: ./.tools/bin/goreleaser release

workflows:
  version: 2
  servicebuilder-cli:
    jobs:
      - shellcheck/check:
          exclude: ./vendor/*
      - build-and-test:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - golangci-lint:
          requires:
            - build-and-test
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - publish-cli:
          requires:
            -  golangci-lint
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
            branches:
              ignore: /.*/